name: Curiosily
description: Misusings on AI, Stats & Programming
meta_description: "Misusings on AI, Stats & Programming"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

logo: false
paginate: 5
baseurl: "" 
domain_name: "http://curiousily.com"

google_analytics: UA-63986975-1

disqus:
  shortname: curiousily

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Details for the RSS feed generator
url: "http://curiousily.com"
author: "Venelin Valkov"
author_bio: "Hi! Thanks for reading all (or some) of it. Find me at <a href='https://twitter.com/curiousily' target='_blank'>Twitter</a> or <a href='https://github.com/curiousily/' target='_blank'>GitHub</a>."
email: venelin@curiousily.com

twitter_username: curiousily
github_username: curiousily

exclude: [notebooks/]
